// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gibbsC
NumericMatrix gibbsC(int N, int thin);
RcppExport SEXP _SA24204134_gibbsC(SEXP NSEXP, SEXP thinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbsC(N, thin));
    return rcpp_result_gen;
END_RCPP
}
// fibonacci_cpp
int fibonacci_cpp(int n);
RcppExport SEXP _SA24204134_fibonacci_cpp(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(fibonacci_cpp(n));
    return rcpp_result_gen;
END_RCPP
}
// sparse_matrix_threshold_cpp
NumericMatrix sparse_matrix_threshold_cpp(NumericMatrix mat, double threshold);
RcppExport SEXP _SA24204134_sparse_matrix_threshold_cpp(SEXP matSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(sparse_matrix_threshold_cpp(mat, threshold));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SA24204134_gibbsC", (DL_FUNC) &_SA24204134_gibbsC, 2},
    {"_SA24204134_fibonacci_cpp", (DL_FUNC) &_SA24204134_fibonacci_cpp, 1},
    {"_SA24204134_sparse_matrix_threshold_cpp", (DL_FUNC) &_SA24204134_sparse_matrix_threshold_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_SA24204134(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
