# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gibbsC <- function(N, thin) {
    .Call('_SA24204134_gibbsC', PACKAGE = 'SA24204134', N, thin)
}

fibonacci_cpp <- function(n) {
    .Call('_SA24204134_fibonacci_cpp', PACKAGE = 'SA24204134', n)
}

sparse_matrix_threshold_cpp <- function(mat, threshold) {
    .Call('_SA24204134_sparse_matrix_threshold_cpp', PACKAGE = 'SA24204134', mat, threshold)
}

